# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: newsmanager 
version: '3.0.2'
author: Friends Of REDAXO 
supportpage: https://github.com/FriendsOfREDAXO/newsmanager/

page:
    title: 'translate:title'
    perm: newsmanager[]
    icon: rex-icon fa-newspaper-o
    subpages:
        main: { title: 'translate:main', icon: rex-icon fa-newspaper-o }
        categories: { title: 'translate:categories', icon: rex-icon fa-tags }
        settings: { perm: 'newsmanagersettings[]', title: 'translate:settings', icon: rex-icon fa-wrench }

requires:
    redaxo: '^5.4' # benötigt mindestens REDAXO 5.4
    packages:
        url: '>1.0.0' # benötig Addon redaxo_url V.2
    php:
        version: '>=5.6' # benötigt mindestens PHP 5.6
conflicts:
    packages:
        url: '<=2.0.0'
installer_ignore:
  - .git
  - .github
  - .gitattributes
  - .gitignore
