package: newsmanager 
version: '3.1.0'
author: Friends Of REDAXO 
supportpage: https://github.com/FriendsOfREDAXO/newsmanager/

page:
    title: 'translate:title'
    perm: newsmanager[]
    icon: rex-icon fa-newspaper-o
    subpages:
        main: { title: 'translate:main', icon: rex-icon fa-newspaper-o }
        categories: { title: 'translate:categories', icon: rex-icon fa-tags }
        settings: { perm: 'newsmanagersettings[]', title: 'translate:settings', icon: rex-icon fa-wrench }

requires:
    redaxo: '^5.15'
    packages:
        neues: '^4'
        url: '^2'
        yform: '^4'
    php:
        version: '>=7.3'
conflicts:
    packages:
        url: '<=2.0.0'
        neues: '<4.0.1'
installer_ignore:
  - .git
  - .github
  - .gitattributes
  - .gitignore
